import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import IframeComponent from "./components/IframeComponent";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Projects Manager",
  description: "Generated by Abderrahmane Raquibi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen flex flex-col">
        <Toaster />
        <div className="flex flex-1 overflow-hidden">
          <Nav />
          {/* Main content wrapper with scrolling */}
          <div className="flex-1 p-4 ml-64 overflow-y-auto max-h-[80vh]">{children}</div>
        </div>
        {/* Make iframe non-blocking */}
        <div className="w-full fixed bottom-0 left-0">
          <IframeComponent />
        </div>
      </body>
    </html>
  );
}



